# Generated by Django 4.2.7 on 2023-11-09 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManagerApp.organization')),
                ('projects', models.ManyToManyField(to='TaskManagerApp.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='super_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManagerApp.user'),
        ),
    ]
