# Generated by Django 4.2.7 on 2023-11-09 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('estimated_time', models.DecimalField(decimal_places=2, max_digits=5)),
                ('label', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManagerApp.project')),
                ('users', models.ManyToManyField(to='TaskManagerApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='SuperUser',
            fields=[
                ('super_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TaskManagerApp.user')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='super_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TaskManagerApp.superuser'),
        ),
    ]
