# Generated by Django 4.2.7 on 2023-11-14 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TaskManagerApp', '0002_admin_task_superuser_alter_project_super_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='user',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='project',
            name='super_user',
        ),
        migrations.AlterField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SuperUser',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
