# Generated by Django 4.2.7 on 2023-11-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0007_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='label',
            field=models.CharField(choices=[('blocked', 'Blocked'), ('bug', 'Bug'), ('content', 'Content'), ('design', 'Design'), ('dev', 'Development'), ('enhancement', 'Enhancement'), ('product', 'Product')], max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Backlog', 'Backlog'), ('Under Progress', 'Under Progress'), ('In Review', 'In Review'), ('Finished', 'Finished')], max_length=255),
        ),
    ]
