# Generated by Django 4.2.7 on 2023-11-17 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0012_project_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='organization_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_id',
            new_name='id',
        ),
    ]
