name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.11 ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set up Environment Variables
        run: |
          cd dev/TaskManager/TaskManager
          echo "DB_NAME=your_db_name" >> .env
          echo "DB_USER=your_user_name" >> .env
          echo "DB_PASS=your_pass" >> .env
          echo "DB_HOST=host" >> .env
          echo "DB_PORT=3306" >> .env
      - name: Run Tests
        run: |
          cd dev/TaskManager
          python manage.py test
